services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P4ssword!Str0ng
      - MSSQL_PID=Express
